source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '10.0'

target 'ZHCNetworking_Example' do
  pod 'ZHCNetworking', :path => '../'
  pod 'Moya'
  pod 'SwiftyJSON'

  target 'ZHCNetworking_Tests' do
    inherit! :search_paths

    
  end
end
